In [1]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import pathlib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [ ]:
# Connecting to Drive
import google
google.colab.drive.mount('/content/drive', force_remount=True)
Main_dir="drive/MyDrive/NASA_Turbofan/"

Mounted at /content/drive


In [ ]:
# Get Train and Test
df_train=pd.read_csv(Main_dir+"Master_train.csv")
df_test=pd.read_csv(Main_dir+"Master_test.csv")

list_to_drop=['Unnamed: 0','Engine_ID','Cycle',]
df_train.drop(list_to_drop, axis=1,inplace=True)
df_test.drop(list_to_drop, axis=1,inplace=True)

In [ ]:
display(df_train)

op1     op2    op3  sensor1  sensor2  sensor3  sensor4  sensor5  \
0       35.0001  0.8406  100.0   449.44   555.07  1366.16  1124.98     5.48   
1       34.9986  0.8414  100.0   449.44   556.00  1366.52  1129.62     5.48   
2        0.0003  0.0002  100.0   518.67   641.90  1581.77  1402.19    14.62   
3       41.9989  0.8413  100.0   445.00   549.52  1352.72  1129.14     3.91   
4       -0.0011  0.0003  100.0   518.67   643.00  1595.74  1406.22    14.62   
...         ...     ...    ...      ...      ...      ...      ...      ...   
128282  42.0079  0.8400  100.0   445.00   549.89  1352.87  1122.11     3.91   
128283   0.0001  0.0006  100.0   518.67   642.80  1600.82  1412.14    14.62   
128284  41.9984  0.8400  100.0   445.00   549.47  1357.41  1121.23     3.91   
128285  10.0027  0.2500  100.0   489.05   604.66  1499.29  1303.47    10.52   
128286   0.0008  0.0000  100.0   518.67   642.49  1589.73  1401.65    14.62   

        sensor6  sensor7  ...  sensor15  sensor16  sensor17  sensor18  \
0          8.00   195.04  ...    9.3198      0.02       333      2223   
1          8.00   197.68  ...    9.1615      0.02       333      2223   
2         21.61   554.45  ...    8.4036      0.03       392      2388   
3          5.71   138.26  ...    9.3767      0.02       332      2212   
4         21.61   553.19  ...    8.4546      0.03       393      2388   
...         ...      ...  ...       ...       ...       ...       ...   
128282     5.72   139.33  ...    9.3230      0.02       330      2212   
128283    21.61   553.38  ...    8.4517      0.03       392      2388   
128284     5.71   139.04  ...    9.3889      0.02       331      2212   
128285    15.49   394.35  ...    8.6373      0.03       369      2319   
128286    21.61   553.66  ...    8.4095      0.03       392      2388   

        sensor19  sensor20  sensor21  RUL  Status  Sub_Status  
0          100.0     14.95    8.9381  163       1     Working  
1          100.0     15.12    8.9427  107       1     Working  
2          100.0     39.04   23.3818  179       1     Working  
3          100.0     10.67    6.3185  156       1     Working  
4          100.0     38.80   23.2919   57       1     Working  
...          ...       ...       ...  ...     ...         ...  
128282     100.0     10.73    6.3476   75       1     Working  
128283     100.0     38.83   23.2863  103       1     Working  
128284     100.0     10.61    6.3123  232       1     Working  
128285     100.0     28.40   17.1430   69       1     Working  
128286     100.0     38.78   23.4348  105       1     Working  

[128287 rows x 27 columns]

In [ ]:
display(df_test)

op1     op2    op3  sensor1  sensor2  sensor3  sensor4  sensor5  \
0      25.0061  0.6203   60.0   462.54   536.98  1262.09  1050.94     7.05   
1       0.0006 -0.0004  100.0   518.67   642.52  1596.85  1407.11    14.62   
2       9.9981  0.2515  100.0   489.05   604.82  1498.32  1311.02    10.52   
3      -0.0024  0.0003  100.0   518.67   642.48  1587.00  1409.25    14.62   
4      41.9986  0.8400  100.0   445.00   550.30  1359.90  1126.98     3.91   
...        ...     ...    ...      ...      ...      ...      ...      ...   
32067  10.0016  0.2519  100.0   489.05   604.73  1500.86  1300.22    10.52   
32068   0.0001  0.0003  100.0   518.67   643.04  1601.88  1413.80    14.62   
32069  20.0023  0.7002  100.0   491.19   607.62  1494.26  1254.59     9.35   
32070  20.0001  0.7000  100.0   491.19   608.01  1482.61  1251.95     9.35   
32071  25.0031  0.6200   60.0   462.54   536.92  1258.92  1058.17     7.05   

       sensor6  sensor7  ...  sensor15  sensor16  sensor17  sensor18  \
0         9.03   175.27  ...   10.9100      0.02       307      1915   
1        21.61   553.29  ...    8.4696      0.03       393      2388   
2        15.49   394.80  ...    8.6637      0.03       369      2319   
3        21.61   554.24  ...    8.4027      0.03       393      2388   
4         5.71   138.49  ...    9.3930      0.02       331      2212   
...        ...      ...  ...       ...       ...       ...       ...   
32067    15.45   395.13  ...    8.6142      0.03       370      2319   
32068    21.61   552.70  ...    8.4791      0.03       395      2388   
32069    13.65   342.05  ...    8.9970      0.03       368      2324   
32070    13.66   333.94  ...    9.2096      0.02       365      2324   
32071     9.03   175.69  ...   10.9383      0.02       309      1915   

       sensor19  sensor20  sensor21  RUL  Status  Sub_Status  
0         84.93     14.14    8.6073  228       1     Working  
1        100.00     38.70   23.2896  107       1     Working  
2        100.00     28.40   17.1504  184       1     Working  
3        100.00     38.78   23.3262   95       1     Working  
4        100.00     10.52    6.2856   91       1     Working  
...         ...       ...       ...  ...     ...         ...  
32067    100.00     28.72   17.1787   89       1     Working  
32068    100.00     38.51   23.1106   43       1     Working  
32069    100.00     24.94   14.9679   15       1     Warning  
32070    100.00     24.28   14.6742   93       1     Working  
32071     84.93     14.07    8.5663   26       1     Warning  

[32072 rows x 27 columns]

### Binary Classification

In [ ]:
drop_list=['RUL','Sub_Status']
df_train.drop(drop_list, axis=1,inplace=True)
df_test.drop(drop_list, axis=1,inplace=True)

In [ ]:
X_train=df_train.drop(['Status'], axis=1)
y_train=df_train['Status']
X_test=df_test.drop(['Status'], axis=1)
y_test=df_test['Status']

In [ ]:
# Random Forest
forest = RandomForestClassifier(random_state=3)
forest.fit(X_train, y_train)

RandomForestClassifier(random_state=3)

In [ ]:
y_pred_test = forest.predict(X_test)

In [ ]:
y_pred_test

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
accuracy_score(y_test, y_pred_test)

0.9839111998004489

In [ ]:
confusion_matrix(y_test, y_pred_test)

array([[ 1147,   271],
       [  245, 30409]])

In [ ]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.82      0.81      0.82      1418
           1       0.99      0.99      0.99     30654

    accuracy                           0.98     32072
   macro avg       0.91      0.90      0.90     32072
weighted avg       0.98      0.98      0.98     32072



### MultiClass Classification

In [ ]:
drop_list=['RUL','Status']
df_train.drop(drop_list, axis=1,inplace=True)
df_test.drop(drop_list, axis=1,inplace=True)

In [ ]:
X_train=df_train.drop(['Sub_Status'], axis=1)
y_train=df_train['Sub_Status']
X_test=df_test.drop(['Sub_Status'], axis=1)
y_test=df_test['Sub_Status']

In [ ]:
# Random Forest
forest = RandomForestClassifier(random_state=3)
forest.fit(X_train, y_train)

RandomForestClassifier(random_state=3)

In [ ]:
y_pred_test = forest.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

    Critical       0.82      0.81      0.81      1418
     Warning       0.71      0.68      0.70      2836
     Working       0.98      0.98      0.98     27818

    accuracy                           0.95     32072
   macro avg       0.84      0.82      0.83     32072
weighted avg       0.95      0.95      0.95     32072



In [ ]:
confusion_matrix(y_test, y_pred_test)

array([[ 1149,   268,     1],
       [  233,  1924,   679],
       [   21,   502, 27295]])

## Regression

In [ ]:
drop_list=['Sub_Status','Status']
df_train.drop(drop_list, axis=1,inplace=True)
df_test.drop(drop_list, axis=1,inplace=True)

In [ ]:
X_train=df_train.drop(['RUL'], axis=1)
y_train=df_train['RUL']
X_test=df_test.drop(['RUL'], axis=1)
y_test=df_test['RUL']

In [ ]:
# Random Forest
forest = RandomForestRegressor(random_state=3)
forest.fit(X_train, y_train)

RandomForestRegressor(random_state=3)

In [ ]:
y_pred_test = forest.predict(X_test)

In [ ]:
MSE=mean_squared_error(y_test, y_pred_test)

In [ ]:
RMSE=MSE**0.5
print(RMSE)

50.360638479935496
